name = "chaingive-web"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
pages_build_output_dir = "out"

[[pages_build_config]]
build_command = "npm run build"
destination_dir = "out"
root_dir = "."

# R2 Storage for static assets
[[r2_buckets]]
binding = "STATIC_ASSETS"
bucket_name = "chaingive-static-assets"
preview_bucket_name = "chaingive-static-assets-preview"

# Environment variables
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://api.chaingive.ng"
NEXT_PUBLIC_SUPABASE_URL = "https://your-project.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"