name: Deploy to Koyeb

on:
  workflow_run:
    workflows: ["Build and Push ChainGive Backend Docker Image"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      
      - name: 🚀 Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          service-name: chaingive-backend
          api-token: ${{ secrets.KOYEB_API_TOKEN }}
