name: EAS Submit to Stores

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to submit'
        required: true
        type: choice
        options:
          - android
          - ios
          - all

jobs:
  submit:
    name: Submit to App Stores
    runs-on: ubuntu-latest
    
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: |
          cd chaingive-mobile
          npm ci

      - name: 📱 Submit to Google Play
        if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' }}
        run: |
          cd chaingive-mobile
          eas submit --platform android --latest --non-interactive

      - name: 📱 Submit to App Store
        if: ${{ github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' }}
        run: |
          cd chaingive-mobile
          eas submit --platform ios --latest --non-interactive
