name: EAS Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - android
          - ios
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: |
          cd chaingive-mobile
          npm ci

      - name: 🚀 Build Android (Preview)
        if: github.ref == 'refs/heads/develop'
        run: |
          cd chaingive-mobile
          eas build --platform android --profile preview --non-interactive --no-wait

      - name: 🚀 Build iOS (Preview)
        if: github.ref == 'refs/heads/develop'
        run: |
          cd chaingive-mobile
          eas build --platform ios --profile preview --non-interactive --no-wait

      - name: 🚀 Build Production (Android)
        if: github.ref == 'refs/heads/main'
        run: |
          cd chaingive-mobile
          eas build --platform android --profile production --non-interactive --no-wait

      - name: 🚀 Build Production (iOS)
        if: github.ref == 'refs/heads/main'
        run: |
          cd chaingive-mobile
          eas build --platform ios --profile production --non-interactive --no-wait

      - name: 📝 Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 EAS Build started! Check your Expo dashboard for progress.'
            })
